---
title: "Info"
author: "Silvia Ventoruzzo"
date: "9/12/2018"
output: html_document
---

# Load packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(DescTools)
library(treemap)
```

# Load datasets

```{r}
aisles <- read.csv(file.path(getwd(), "instacart-market-basket-analysis", "aisles.csv", fsep="/"))
departments <- read.csv(file.path(getwd(), "instacart-market-basket-analysis", "departments.csv", fsep="/"))
order_products_prior <- read.csv(file.path(getwd(), "instacart-market-basket-analysis", "order_products__prior.csv", fsep="/"))
# order_products_train <- read.csv(file.path(getwd(), "instacart-market-basket-analysis", "order_products__train.csv", fsep="/"))
orders <- read.csv(file.path(getwd(), "instacart-market-basket-analysis", "orders.csv", fsep="/"))
products <- read.csv(file.path(getwd(), "instacart-market-basket-analysis", "products.csv", fsep="/"))
```

# Organize dataframes

```{r}
# Check for missing values
apply(orders, 2, function(x) any(is.na(x)))
orders %>% filter(is.na(days_since_prior_order)) %>% group_by(order_number) %>% summarize(count = n()) # all 1s

apply(order_products_prior, 2, function(x) any(is.na(x))) # 0

apply(products, 2, function(x) any(is.na(x))) # 0

# Renaming and reordering factors for order_dow
orders <- orders %>%
  mutate(order_dow = recode_factor(as.factor(order_dow),
                            "1" = "Monday",
                            "2" = "Tuesday",
                            "3" = "Wednesday",
                            "4" = "Thursday",
                            "5" = "Friday",
                            "6" = "Saturday",
                            "0" = "Sunday"))

# Join products, aisles and departments
products <- products %>%
  left_join(aisles, by = "aisle_id") %>%
  left_join(departments, by = "department_id") %>%
  select(product_id, product_name,
         aisle_id, aisle,
         department_id, department)

# Change missing to other in aisles_departments and products
products %>% 
  filter(department == "missing" | department == "other" |
                    aisle == "missing" | aisle == "other") %>%
  distinct(aisle_id, aisle, department_id, department)
# other: aisle_id = 6, department_id = 2
# missing: aisle_id = 100, department_id = 21

products <- products %>%
  mutate(department_id = replace(department_id, department == "missing", 2),
         department = replace(department, department == "missing", "other"),
         aisle_id = replace(aisle_id, aisle == "missing", 6),
         aisle = replace(aisle, aisle == "missing", "other")) %>%
  droplevels()

rm("aisles", "departments")
```

Plots
```{r}
# hour_of_day distribution
orders_train %>% 
  ggplot() +
  geom_histogram(aes(x = as.factor(hour_of_day)), stat="count", fill = "blue") +
  labs(x = "Hour of the day")

# day_of_week distribution
orders_train %>%
  ggplot() +
  geom_histogram(aes(x = as.factor(day_of_week)), stat="count", fill = "orange") +
  labs(x = "Day of the week") # need to understand how to reorder factor levels!

# days_since_prior_order distribution
orders_train %>%
  ggplot() +
  geom_histogram(aes(x = days_since_prior_order), stat="count", fill = "dark green") +
  labs(x = "Days since prior order") 

# day_of_week, hour_of_day mosaic plot
day_hour <- table(orders_train$day_of_week, orders_train$hour_of_day)
mosaicplot(day_hour, 
           main = "Mosaic plot of order day and hour",
           xlab = "Day of the week",
           ylab = "Hour of the day",
           shade = TRUE)

# Items per order distribution
orders_train %>%
  group_by(order_id) %>%
  summarize(order_amount = n()) %>%
  ggplot() +
  geom_histogram(aes(x = order_amount), stat="count", fill = "pink") +
  labs(x = "Items per order") 

# Most ordered products
# it either takes too long or it doesn't work
orders_train %>%
  ggplot() +
  geom_histogram(aes(x = product), stat="count", fill = "yellow") +
  labs(x = "Products")

orders_train %>%
  group_by(product) %>%
  summarize(count = n()) %>%
  ggplot() +
  geom_histogram(aes(x = product, y = count), stat="identity", fill = "yellow") +
  labs(x = "Products") 


```

# Treemap aisles/department

```{r}
products %>%
  group_by(department, aisle) %>%
  summarize(count = n()) %>%
  treemap(dtf = .,
          index = c("department", "aisle"),
          vSize = "count",
          type = "index",
          palette = "Spectral",
          title = "Products per department and aisle")

products %>%
  group_by(department) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

products %>%
  group_by(aisle) %>%
  summarize(count = n()) %>%
  arrange(desc(count))
```