---
title: "Principal Component and Factor Analysis"
author: "Silvia Ventoruzzo"
date: "26/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
p_load(psych)
```

# PCA of user_aisle_share

First we need to decide if to use the covariance or the correlation matrix, therefore we need to check the measures and variance of the variables

```{r}
# Measure: all variables are measured the same since they are counts

# Variance
describe(user_aisle_share[,-1]) %>%
  mutate(variable = rownames(.),
         var = sd^2) %>%
  summarize(var_bw_variables = var(var))
```

Choose the number of components

```{r}
scree_plot <- scree(user_aisle_share[,-1])

scree_pca <- scree_plot[["pcv"]] %>%
  as.data.frame() %>%
  rename("pcv" = ".") %>%
  arrange(desc(pcv)) %>%
  mutate(pc = as.integer(rownames(.)),
         kaiser = ifelse(pcv > 1, TRUE, FALSE),
         ellbow = lead(pcv, default = 1) - pcv,
         percent = cumsum(prcomp(user_aisle_share[,-1], scale. = TRUE)$sdev^2/ncol(user_aisle_share[,-1])))

scree_pca %>%
  filter(pc == max(pc[kaiser == "TRUE"])) %>%
  select(pc)
# Kaiser Criterium: 41

scree_pca %>%
  filter(abs(ellbow) == max(abs(ellbow))) %>%
  select(pc)
# Ellbow Criterium: 7 - from plot

scree_pca %>%
  filter(pc == min(pc[percent >= 0.7]) |
         pc == min(pc[percent >= 0.9])) %>%
  select(pc, percent)
# 70% Criterium: 85
# 90% Criterium: 116

rm("scree_plot", "scree_pca")
```

Actual principal component analysis

```{r}
pca <- psych::principal(user_aisle_share[,-1], rotate="none", nfactors = 41)
pca
prcomp <- prcomp(user_aisle_share[,-1], scale. = TRUE)
prcomp
```

# FA of user_aisle_share

Suitability of factor analysis

```{r}
psych::KMO(user_aisle_share[,-1])
```

How many factors?

```{r}
# Ellbow: 7 - like for PCA
# Kaiser: 41 - like for PCA
fa.parallel(user_aisle_share[,-1], fa="pc") # horn: ?
fa.parallel(user_aisle_share[,-1], fa="fa") # horn: ?
```
